services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app-company
      - app-student
    networks:
      - applift_network

  app-company:
    build:
      context: ./company
    container_name: app-company
    volumes:
      - ./company:/var/www/html
      - ./company/nginx/nginx.conf:/etc/nginx/nginx.conf
    # ports:
      # - "5173:5173" # Viteの開発サーバー用
    networks:
      - applift_network
    depends_on:
      - db
      - mailhog

  app-student:
    build:
      context: ./student
    container_name: app-student
    volumes:
      - ./student:/var/www/html
      - ./student/nginx/nginx.conf:/etc/nginx/nginx.conf
    # ports:
    #   - "5174:5174" # Viteの開発サーバー用
    networks:
      - applift_network
    depends_on:
      - db
      - mailhog

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"  # DBクライアント接続用
    networks:
      - applift_network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - applift_network

volumes:
  db_data:

networks:
  applift_network:
    external: true
