FROM php:8.3-fpm

RUN docker-php-ext-install pdo pdo_mysql

# Nginxのインストールと mime.types ファイルのインストール
# mime.typesファイルの存在確認
RUN apt-get update && apt-get install -y nginx \
    && mkdir -p /etc/nginx \
    && curl -o /etc/nginx/mime.types https://raw.githubusercontent.com/nginx/nginx/master/conf/mime.types \
    && ls /etc/nginx/mime.types

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN chown -R www-data:www-data /var/www/html

# Composerのインストールとキャッシュクリア
RUN composer install --optimize-autoloader --no-dev \
    && php artisan config:cache \
    && php artisan route:cache

# Nginxの設定を追加
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# NginxとPHP-FPMをフォアグラウンドで起動
CMD ["sh", "-c", "nginx -g 'daemon off;' & php-fpm"]
